name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    env:
      IMAGE: europe-west2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/pauljs-io/homepage

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci && npx semantic-release
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v0.8.3"
        with:
          workload_identity_provider: ${{ secrets.WI_PROVIDER }}
          service_account: ${{ secrets.GSA_REGISTRY }}

      - name: Authenticate Docker
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Setup Docker BuildKit
        uses: docker/setup-buildx-action@v2

      - name: Build & Publish Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ steps.get-next-version.outputs.new-release-version }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max

      - name: Release
        run: npm ci && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEPAGE_RELEASE_TOKEN }}